CONFIG_NAME: xray

dataset_name: xray
data_dir: /data/coding/bggan/data/xray

gpu_id: 0
imsize: 256
z_dim: 100
cond_dim: 256
manual_seed: 100
cuda: True

stamp: 'normal'
state_epoch: 0
max_epoch: 601
batch_size: 32
nf: 32
ch_size: 3

model: base

gen_interval: 5
test_interval: 10
save_interval: 10

truncation: True
trunc_rate: 0.88

sample_times: 10
npz_path: /data/coding/bggan/data/xray/npz/xray_val256_FIDK0.npz
example_captions: ./example_captions/xray.txt
samples_save_dir: ./samples/xray/
checkpoint: ./saved_models/xray/pretrained/state_epoch_290.pth

save_image: False
val_save_dir: ./vals/xray/

TEXT:
    WORDS_NUM: 195
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 1
    DAMSM_NAME: /data/coding/bggan/data/xray/DAMSMencoder/text_encoder550.pth
    