CONFIG_NAME: xray

dataset_name: xray
data_dir: /data/bggan/data/xray

gpu_id: 0
imsize: 256
z_dim: 100
cond_dim: 256
manual_seed: 100
cuda: True

stamp: 'normal'
state_epoch: 0
max_epoch: 601
batch_size: 32
nf: 32
ch_size: 3

model: base

gen_interval: 1
test_interval: 10
save_interval: 10

truncation: True
trunc_rate: 0.88

sample_times: 10
npz_path: /data/bggan/data/xray/npz/xray_val256_FIDK0.npz
example_captions: /data/bggan/code/example_captions/heart.txt
samples_save_dir: /data/bggan/code/samples/heart/t2i/
samples_i2t_save_dir: /data/bggan/code/samples/xray/i2t/
samples_i2i_save_dir: /data/bggan/code/samples/xray/i2i/
checkpoint: /data/bggan/code/savemodel/state_epoch_600.pth

save_image: False
val_save_dir: /data/bggan/code/vals/heart/

TEXT:
    WORDS_NUM: 62
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 1
    DAMSM_NAME: /data/bggan/data/xray/DAMSMencoder/text_encoder550.pth
